
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waylau/spring-cloud-microservices-development.git
          search-paths: config-repo
  application:
    name: msa-weather-config-server